### ISSUE TITLE
Ticker data through WAMP

### ISSUE THREAD

**Issue by cyzanfar** [s4w3d0ff/python-poloniex#115] opened 2017-05-19 16:33 UTC
I'm trying to get a continuous flow of ticker data for a currency pair (i.e `BTC_USDT`)

```python
if __name__ == '__main__':
    from time import sleep
    ticker = Ticker()
    ticker.start()
    for i in range(100):
        sleep(3)
        print "BTC_USD: last= {} baseVolume= {}".format(ticker()['last'], ticker()["baseVolume"])

    ticker.stop()
    print("Done")
```

However when I print the output it shows me the same price everytime. Am I missing something ?

```
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
BTC_USD: last= 1949.64570488 baseVolume= 19152881.89583429
```

**Comment by s4w3d0ff** [comment] 2017-05-19 21:31
I tested the mongoTicker.py on python2 and was getting:
```
2017-05-19T12:49:55-0700 dropping connection to peer tcp4:104.20.12.48:443 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
USDT_BTC: lowestAsk= 1229.98000000
USDT_BTC: lowestAsk= 1229.98000000
USDT_BTC: lowestAsk= 1229.98000000
USDT_BTC: lowestAsk= 1229.98000000
USDT_BTC: lowestAsk= 1229.98000000
2017-05-19T12:50:42-0700 Received SIGTERM, shutting down.
2017-05-19T12:50:42-0700 Main loop terminated.
Done
```
Looks like it isn't connecting to the api.

I have a [working python3 version](https://github.com/s4w3d0ff/marconibot/blob/master/marconi/pushy.py) using a portion of https://github.com/absortium/poloniex-api(https://github.com/s4w3d0ff/marconibot/tree/master/marconi/tools/poloniex/push). But you will probably have to hack it apart.

**Comment by cyzanfar** [comment] 2017-05-20 16:06
Could this be because of the timeout default set? https://github.com/crossbario/crossbar/issues/930

**Comment by s4w3d0ff** [comment] 2017-05-21 03:40
Probably, that issue seems like it is for the websocket server but I am sure there is a similar param for the client side. Not sure how to access it though...

**Comment by cyzanfar** [comment] 2017-05-21 14:41
Yeah same here. Thanks for the reply. Will look into it 👍

**Comment by cyzanfar** [comment] 2017-05-23 02:50
@s4w3d0ff did you get a look at this issue ? i'm struggling with it right now. Does any body else experiencing the same issue ?

**Comment by s4w3d0ff** [comment] 2017-05-23 03:08
No, I have yet to, after some brief poking all I could find was refs to: https://github.com/isra17/autobahn-autoreconnect (asyncio). I need to browse the docs again and see if I missed something.

**Comment by cyzanfar** [comment] 2017-05-23 03:11
Took a look at that too but it seems like that's only for retries on 'error'.  Our particular issue here looks like it's coming from the initial handshake timing out before it's even confirmed.

**Comment by tombrekelmans** [comment] 2017-05-29 10:36
This seems to work.

from twisted.internet.ssl import CertificateOptions
options = CertificateOptions()
app_runner = ApplicationRunner(u"wss://api.poloniex.com:443", u"realm1", ssl=options)

**Comment by cyzanfar** [comment] 2017-05-29 14:17
@tombrekelmans nice one. That worked for me too.

**Comment by CfirTsabari** [comment] 2017-06-04 07:41
@tombrekelmans it's seem that i also have problems with the ssl certificate but the solution that you posted didn't work for me,
 do you have any idea how to check it?

**Comment by shlinx** [comment] 2017-06-05 03:57
@tombrekelmans I've got the same issue as well. I've tried your solution, but it raised an exception as below, on CPython 3.6.1:
```
Traceback (most recent call last):
  File "./frontend.py", line 58, in <module>
    main()
  File "./frontend.py", line 54, in main
    runner.run(PoloniexComponent)
  File "/Users/xlin/.pyenv/versions/3.6.1/lib/python3.6/site-packages/autobahn/asyncio/wamp.py", line 256, in run
    (transport, protocol) = loop.run_until_complete(coro)
  File "/Users/xlin/.pyenv/versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/xlin/.pyenv/versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 802, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Users/xlin/.pyenv/versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 828, in _create_connection_transport
    yield from waiter
  File "/Users/xlin/.pyenv/versions/3.6.1/lib/python3.6/asyncio/sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "/Users/xlin/.pyenv/versions/3.6.1/lib/python3.6/asyncio/sslproto.py", line 636, in _process_write_backlog
    self._on_handshake_complete)
  File "/Users/xlin/.pyenv/versions/3.6.1/lib/python3.6/asyncio/sslproto.py", line 129, in do_handshake
    self._sslobj = self._context.wrap_bio(
AttributeError: 'OpenSSLCertificateOptions' object has no attribute 'wrap_bio'
```
Any thoughts?

**Comment by tombrekelmans** [comment] 2017-06-05 04:56
Sorry I'm on python 2.7, don't know.

**Comment by CfirTsabari** [comment] 2017-06-05 09:41
So if anybody still looking for an answer because @tombrekelmans  solution didn't work for him  and they are working with windows i found the answer.
So i am no expert so i dont for sure why this solution work, i figured it's related to the TLS version because it's used to work until what i assumed  was software change on Poloniex side(i think), also i sniffed the TCP connection and saw that i keep receiving Encryption Alert.
So what @sofiryef did was adding a to the registry a new branch called TLS 1.0 ,the reason for doing is still unknown for the both of us, bey if it's work ....
so i have attached the registry branch file so you can just import it ,probably best to backup your registry before doing it.
for some reason the connection is getting timeout a lot so just keep trying to reconnect.

**Comment by cyzanfar** [comment] 2017-06-05 19:20
@CfirTsabari What code should be updated in order to make the socket connection handshake work ?

**Comment by sofiryef** [comment] 2017-06-05 20:00
@cyzanfar : No code change. just need to add this registry branch to your registry using regedit.exe.
But notice that this solved the problem that occurred *after* the initial handshake.

**Comment by Vadus** [comment] 2017-06-06 20:02
executing the example with wamp subscription will lead to the same handshake timeout error:
`
~/ » git clone https://github.com/s4w3d0ff/python-poloniex.git && cd python-poloniex/examples
Cloning into 'python-poloniex'...
remote: Counting objects: 1370, done.
remote: Total 1370 (delta 0), reused 0 (delta 0), pack-reused 1370
Receiving objects: 100% (1370/1370), 231.54 KiB | 98.00 KiB/s, done.
Resolving deltas: 100% (718/718), done.
Checking connectivity... done.
------------------------------------------------------------
~/python-poloniex/examples(master) » python polocalbox.py 
2017-06-06T21:57:43+0200 dropping connection to peer tcp4:104.20.13.48:443 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
`
python is python2.7 at my ubuntu

**Comment by s4w3d0ff** [comment] 2017-06-08 18:56
Since the trollbox has been removed, I wouldn't expect the polocalbox.py to work anymore, I will be removing it from the examples (along with the recently added trollbox message command).

**Comment by hockeyadc** [comment] 2017-06-14 22:55
Forgive me, but where is the registry branch?

**Comment by fship7** [comment] 2017-06-26 03:40
i have had some limited success (sometimes the handshake goes through) by increasing the handshake timeout, as previously suggested. using asyncio you edit wamp.py, line 227

**Comment by CfirTsabari** [comment] 2017-06-26 07:46
@hockeyadc next time try to mention the person that you want to see your comment,
i have fixed the comment so it will include the file.
@fship7 but don't use the Poloniex Wamp protocol which isn't good and have mega latency issues(~9 hours).
instead use their normal protocol(that isn't documented but they use in their website so you can look at the source code of the website(js)).
if you want i can help you with that.

**Comment by fship7** [comment] 2017-06-26 20:35
@CfirTsabari I assume the website javascript you refer to is 
https://poloniex.com/js/plx_exchage.js?v=060617
As far as I can tell it uses websockets, which gets set up in the function "initWebSockets"
Are you saying drop WAMP in favor of websockets?

**Comment by fship7** [comment] 2017-06-27 14:56
I think @CfirTsabari is probably right but I have no idea how to implement his idea in python. Notice that the file https://poloniex.com/js/plx_exchage.js?v=060617 contains a function "initWebSockets_new()" which calls wss://api2.poloniex.com   Is this the function used on the website? I'm not sure, I'm not good enough with the profiler to figure that out.
Perhaps this is the way to go, I'm not sure.

**Comment by elephanter** [comment] 2017-06-27 17:55
hello. Thanks for js sources. In python it looks like this
but. unfortunately I have to restart it many times, because in most cases i've got time out 
```
import websocket
import thread
import time
import json

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    print("ONOPEN")
    def run(*args):
        ws.send(json.dumps({'command':'subscribe','channel':1001}))
        ws.send(json.dumps({'command':'subscribe','channel':1002}))
        ws.send(json.dumps({'command':'subscribe','channel':1003}))
        ws.send(json.dumps({'command':'subscribe','channel':'BTC_XMR'}))
        while True:
            time.sleep(1)
        ws.close()
        print("thread terminating...")
    thread.start_new_thread(run, ())


if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://api2.poloniex.com/",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()
```

**Comment by fship7** [comment] 2017-06-27 21:35
@elephanter Great work. I have not had any problems with connecting. Your websocket method seems to have much less latency than the WAMP method. In case you are interested in the translation of the number to currency-pair that channel 1002 spits out, you can check this paste I just made, or simply look at the page source when you are on the exchange: https://pastebin.com/f8G294hE

**Comment by s4w3d0ff** [comment] 2017-06-28 19:40
Added a working websocket mongodb example: https://github.com/s4w3d0ff/python-poloniex/commit/2e4e517d0eeefab560f2e12b8609238b7a49d288
It requires the above mentioned websocket library: `pip install websocket-client`
```
s4w3d0ff@8core/m/s/E/P/p/e/ticker> python wsMongoTicker.py  
Thread started
Populated markets database with ticker data
Subscribed to ticker
{u'_id': u'USDT_BTC',
 u'baseVolume': u'45230807.65886496',
 u'high24hr': u'2517.30391393',
 u'highestBid': u'2489.00000001',
 u'id': 121.0,
 u'isFrozen': 0,
 u'last': u'2489.00000001',
 u'low24hr': u'2337.44671653',
 u'lowestAsk': u'2489.50000000',
 u'percentChange': u'0.05421431',
 u'quoteVolume': u'18429.91629320'}
{u'_id': u'USDT_BTC',
 u'baseVolume': u'45230807.65886496',
 u'high24hr': u'2517.30391393',
 u'highestBid': u'2489.00000001',
 u'id': 121.0,
 u'isFrozen': 0,
 u'last': u'2489.50000000',
 u'low24hr': u'2337.44671653',
 u'lowestAsk': u'2490.00000000',
 u'percentChange': u'0.05515242',
 u'quoteVolume': u'18429.91629320'}
{u'_id': u'USDT_BTC',
 u'baseVolume': u'45229977.64312600',
 u'high24hr': u'2517.30391393',
 u'highestBid': u'2486.72847710',
 u'id': 121.0,
 u'isFrozen': 0,
 u'last': u'2489.49999999',
 u'low24hr': u'2337.44671653',
 u'lowestAsk': u'2490.00000000',
 u'percentChange': u'0.05574948',
 u'quoteVolume': u'18429.47645382'}
{u'_id': u'USDT_BTC',
 u'baseVolume': u'45229977.64312600',
 u'high24hr': u'2517.30391393',
 u'highestBid': u'2486.72847710',
 u'id': 121.0,
 u'isFrozen': 0,
 u'last': u'2489.49999999',
 u'low24hr': u'2337.44671653',
 u'lowestAsk': u'2490.00000000',
 u'percentChange': u'0.05574948',
 u'quoteVolume': u'18429.47645382'}
{u'_id': u'USDT_BTC',
 u'baseVolume': u'45229977.64312600',
 u'high24hr': u'2517.30391393',
 u'highestBid': u'2485.50000000',
 u'id': 121.0,
 u'isFrozen': 0,
 u'last': u'2486.72847710',
 u'low24hr': u'2337.44671653',
 u'lowestAsk': u'2486.72847710',
 u'percentChange': u'0.05462157',
 u'quoteVolume': u'18429.47645382'}
Websocket closed!
Thread joined
```

BTW the channels are:

1001 = trollbox (you will get nothing but a heartbeat)
1002 = ticker
1003 = base coin 24h volume stats
1010 = heartbeat
'MARKET_PAIR' = market order books

other channels are either heartbeats or you have to be logged in to use (I'm guessing)

**Comment by s4w3d0ff** [comment] 2017-07-01 19:14
If you are still trying to get autobahn to work and still get TLS handshake errors you can try:
https://stackoverflow.com/a/38254622/3389859

**Comment by CfirTsabari** [comment] 2017-07-02 15:00
@s4w3d0ff the solution using certifi didn't worked for me(i did the registry thing).
@fship7 the correct way to translate the id's arrive from the '1002' is to use the the returnTicker get request-[like this](https://poloniex.com/public?command=returnTicker)
ohh and i am thinking of writing an example on how to parse the data from the web socket you think this will be of any help to you?

**Comment by CfirTsabari** [comment] 2017-07-02 16:10
hi guys,
@s4w3d0ff @fship7 @elephanter @hockeyadc 
i have created an example code that parse the web socket data.
[the code is here](https://pastebin.com/wJbTWWDK) i have used [websockets](https://pypi.python.org/pypi/websockets).
enjoy

**Comment by mellertson** [comment] 2017-07-18 12:53
@CfirTsabari I'm having trouble setting up Python 3.5, and only have Python 3.4 presently.  Most of my experience with is with Python 2.7.x. Based on my reading of PEP 492, it looks to me like the `async` keyword is only available in Python 3.5.

Is there any way to re-tool your code so it's compatible with Python 3.4? I've tried replacing `async` with the `@asyncio.coroutine` decorator, but I haven't had success running your code after making this change.

**Comment by CfirTsabari** [comment] 2017-07-25 07:43
@mellertson i assume you are working on linux and not windows since on windows it's pretty simple(yuou can install python version at different locations if this is the problem),if i am wrong and you are working on windows please try again ,python 3.6 is top of the art python version .

Now about the the code not working even after changeing `async` to '@asyncio.coroutine' : 
I think  you should also change 'await' to 'yield from' and you can see an example [here](https://docs.python.org/3.4/library/asyncio-task.html#asyncio-date-coroutine).

Also 'async with' is not available at python 3.4 (more info about this can be found [here](https://docs.python.org/3.4/library/asyncio-task.html#asyncio-date-coroutine) so you should 
either : 
-not use  with and use 'yield from' and release the websocket at the end of the connection
or
-just use 'with' and let the connect function block you(i think this should work i am not sure)

anyway good luck

**Comment by DanielClaudeBaeriswyl** [comment] 2017-09-07 11:50
Hi all,

Is there a way to send orders via websocket to Poloniex ?

**Comment by CfirTsabari** [comment] 2017-09-07 15:39
@DanielClaudeBaeriswyl 
hi,
no you can't.

**Comment by s4w3d0ff** [comment] 2017-09-07 15:52
@DanielClaudeBaeriswyl the problem is authenticating with the websocket so you can make orders, and then finding the right channel to send the requests to (without proper documentation). I don't think simply adding headers with a signed api key will work (although I haven't tried).

**Comment by CfirTsabari** [comment] 2017-09-07 16:17
@s4w3d0ff @DanielClaudeBaeriswyl 
hello,
the authentication to the web socket is not by using the API_KEY and the Secret, it's something more similar to the authentication to the website(user\password\2 step verification).
Also even if you succeed in authenticating to the web socket(which is totally doable) , you still won't be able to send orders but only to received updates about your trades(and maybe updates on your opened orders i am not sure).

**Comment by cyzanfar** [comment] 2017-09-07 16:41
What do you guys think about the FIX API as a mean of passing orders and
receiving update from the orders you passed ?

**Comment by CfirTsabari** [comment] 2017-09-07 16:47
@cyzanfar 
hello,
Well the FIX API is great for this ,since it was developed for this.
I can tell that a lot of the problems that presence in the HTTP API will not be an issue in a FIX API.
Only one problem ,Poloniex doesn't support one or at least it's not on thier API page.

**Comment by mellertson** [comment] 2017-09-07 19:26
@DanielClaudeBaeriswyl
At the bottom of [s4w3d0ff's example page](https://github.com/s4w3d0ff/python-poloniex/tree/master/examples), he provides a reference to [Absortium's repo](https://github.com/absortium/poloniex-api), poloniex-api. There are `buy()` and `sell()` methods, I've used them both successfully. They're pretty easy to use. The only caviate I've run into is the `buy()` / `sell() `methods will often return an order ID before the order is actually placed on Poloniex's order book. I created a  method called `waitForTrade()` which polls the trades for a given order ID, so that I can verify the order was placed and actually traded.  Here's an example I threw together:

    from poloniex.api.sync import TradingApi
    from time import sleep
    
    # create an api object, using a private api key and secret
    api = TradingApi(api_key="api_key_goes_here", api_sec="api_secret_goes_here")
    
    # place a buy order on Poloniex
    orderID = api.buy(currency_pair='USDT_BTC', rate=0.000235, amount=0.25)
    
    # wait for the order to be placed
    traded = False
    while not traded:
        sleep(1.0/8.0)
	try:
	    trades = api.returnOrderTrades(order_number=orderID)
	    for trade in trades:
	         aQuantity += float(trade['amount'])
	         if aQuantity >= 0.25:
		    traded = True
	         
	except PoloniexError as e:
	    if str(e).startswith('Order not found'):
		print('WARNING: Order not found after placing order: {}'.format(orderID))

**Comment by s4w3d0ff** [comment] 2017-09-07 22:33
@mellertson I am pretty sure those are still REST api calls under the hood and doesn't send the api requests through the WAMP or websocket

**Comment by mellertson** [comment] 2017-09-10 18:26
@s4w3d0ff 
Yes, I believe you are correct.  I spent about a week trying to get WAMP or Autobahn to work.  I was able to get ticker data streaming in, but it seemed to sporadically miss some of the ticker data.  I tried many different versions of code and libraries. One that seemed to be fast and stable I pulled directly from Ricky Han's answer from the [stackoverflow question](https://stackoverflow.com/questions/32154121/how-to-connect-to-poloniex-com-websocket-api-using-a-python-library/38254622#38254622) s4w3d0ff posted earlier in this thread.   

I finally decided to implement the code I posted in my comment, 2 comments above. But, the code I'm posting here worked quite well.  It's based on Python 2.7 and uses the websocket library. 

    import websocket
	import thread
	import time
	import json
	
	def on_message(ws, message):
		print(message)
	
	def on_error(ws, error):
		print(error)
	
	def on_close(ws):
		print("### closed ###")
	
	def on_open(ws):
		print("ONOPEN")
		def run(*args):
			ws.send(json.dumps({'command':'subscribe','channel':1001}))
			ws.send(json.dumps({'command':'subscribe','channel':1002}))
			ws.send(json.dumps({'command':'subscribe','channel':1003}))
			ws.send(json.dumps({'command':'subscribe','channel':'BTC_XMR'}))
			while True:
				time.sleep(1)
			ws.close()
			print("thread terminating...")
		thread.start_new_thread(run, ())
	
	
	if __name__ == "__main__":
		websocket.enableTrace(True)
		ws = websocket.WebSocketApp("wss://api2.poloniex.com/",
								  on_message = on_message,
								  on_error = on_error,
								  on_close = on_close)
		ws.on_open = on_open
		ws.run_forever()

**Comment by spradlig** [comment] 2017-09-25 21:41
Has anyone figured out how to authenticate to the private/logged in websocket (Channel 1000)? Having my own trade data with a minimum of latency would be ideal.

I've dug through the JS on the site (not a language I've coded in). I've captured a frame where my authentication data was visible. Looking at the JS code I'm clearly missing something since it appears that all I should have to do is pass a UserID like so {'command': 'subscribe', 'channel': 1000., 'userid': 123456}. But that didn't work. (Seems like pretty horrible security if it did work.)

**Comment by CfirTsabari** [comment] 2017-09-25 21:48
@spradlig if i remember correctly the either the connection ot the specific frame(i put my money on the connection) ,has header with cookies that somehow hold information about the authentication.

**Comment by spradlig** [comment] 2017-09-25 22:11
From what I remember of looking at the page after log in there wasn't a lot in the cookies but there was a Poloniex Session ID. I wondered if that needed to be provided (and tried several ways of providing it without success).

@CfirTsabari have you tried a wget on the Polo site? I have not - yet. From what I remember there is private.php file that seems to generate a lot of data the JS needs for an authenticated connection.

Hmmm.... Should I curse Polo for making it this hard or praise them since it means fewer competing bots?

**Comment by CfirTsabari** [comment] 2017-09-25 22:17
@spradlig
Dont praise them, bots is good for ab exchange(as long its third party bots and not the exchange bots).
I didn't tried wget but i did tried inspect using chrome which is good enough.
If i remember right it's has something to do with the headers.
Sorry i can't currently help more than that.

**Comment by spradlig** [comment] 2017-09-25 23:38
@CfirTsabari Agreed, bots are good for liquidity. I just meant higher hurdles mean fewer bots my bot will have to compete with.

Thanks again

**Comment by jonathan-s** [comment] 2017-12-24 21:40
@s4w3d0ff I was wondering if you had any clue of when you subscribe to a currency pair through websockets. The following is an example of the kind of data that you get. 

```
[114,262589046,[["o",1,"0.02375014","0.00000000"],["o",1,"0.02375016","178.68700000"]]]
```
* 114 is the id. 
* `262589046` I don't know. It seems like it's an internal id for the order perhaps, as it's sequential. 
* An array of orders.
- `o` seems to always be the same. 
- `1` is either one or zero. Buy and sell?
- `0.02375014`, the rate?
- `0.00000000`, amount? But why would it be zero?

**Comment by CfirTsabari** [comment] 2017-12-25 08:22
@jonathan-s

hi jonathan,
have you read this entire thread before posting?
because if you did you should have seen this [post](https://github.com/s4w3d0ff/python-poloniex/issues/115#issuecomment-312500814) which state that i have created an example that show how to parse and handle the web socket data, with comments and all,
enjoy 
[just go here](https://pastebin.com/wJbTWWDK
)
-  262589046 is the sequnce id of the update ,you should verify this go up one at a time so you won't miss updates.
 - not an array of orders but an array of updates.
- "o" -this mean update related to the order book ,"i"-this mean snapshot,"t" this mean trade update
-Order Update:
-- 1- yes , one mean buy and zero mean sell
-- 0.02375014 yes this is rate
-- 0.00000000 yes amount while zero mean remove level,other values mean add or update

**Comment by jonathan-s** [comment] 2017-12-25 08:33
@CfirTsabari, I did read the entire thread, but didn't click that particular link. Thank you for clarifying!

**Comment by JohnVonNeumann** [comment] 2018-01-21 07:05
@CfirTsabari When running your code on Py35 and Py36 I get a

"Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "app2.py", line 51, in _start_subscriber
    self._event_loop.run_until_complete(self._subscribe())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "app2.py", line 54, in _subscribe
    async with websocket.connect(API_LINK) as websocket:
UnboundLocalError: local variable 'websocket' referenced before assignment"

Cheers for the example, proving very useful for understanding, I don't get why they don't provide more documentation.

**Comment by CfirTsabari** [comment] 2018-01-21 09:06
@sofiryef @JohnVonNeumann 
hi,
first of all thank you,also about Poloniex not providing a documentation in my opinion they are over swamped.
And lastly look like you had a copy error,
this line `async with websocket.connect(API_LINK) as websocket:`
should be `async with websockets.connect(API_LINK) as websocket:`
have fun,

**Comment by sofiryef** [comment] 2018-01-21 10:56
איזה גבר!

**Comment by davidlr99** [comment] 2018-01-21 19:36
@CfirTsabari Thanks for your explanations! One question left: 
When there is a orderbook update ("o" tag) you said that "other values mean add or update". How do I know If I have to "update" (replace old value with the new value) or if I have to add the new amount to the old value (add up)? 

Regards,
David

**Comment by CfirTsabari** [comment] 2018-01-21 20:43
@davidlr99 
hi,
i am not sure if you are asking what to do on update, or if you are asking what's the difference between add and update, so i am going to give an answer that will hopefully answer both of this questions.
so 'add or update' mean that you don't know if it's 'add' or 'update' ,also this shouldn't be relevant .
Since update mean override the last value there is no real difference in how to handle add or how to handle update, lets say that you hold a map that represents one side of the book in both cases the code should be the same:`book_side[price]=size`

**Comment by JohnVonNeumann** [comment] 2018-01-21 22:53
@CfirTsabari It's not that actually, I got this error because websockets was unrecognised as a dependency. What version of python did you write your script in?

**Comment by CfirTsabari** [comment] 2018-01-21 23:02
@JohnVonNeumann 
i think i have used python 3.4 but i am not sure any how i don't think this is relevant 
first ,its clear from what you uploaded here that you didn't copy the code correctly (or you didn't copy here the correct output), it should be websockets.connect and not websocket.connect no point in arguing this, i can also tell that from the error.
you might have another problem that is related to not installing the package websockets, this can be easily fixed by using `pip install websockets` in order to install the package.

**Comment by JohnVonNeumann** [comment] 2018-01-21 23:03
@CfirTsabari Wait you didn't use https://github.com/websocket-client/websocket-client?

Their file level import is websocket, so I just assumed it was that one? Can you link me to the docs of which lib you're using?

**Comment by CfirTsabari** [comment] 2018-01-21 23:19
@JohnVonNeumann 
hi,
no i used websocket**s** which you can find [here](https://pypi.python.org/pypi/websockets/4.0.1),

**Comment by JohnVonNeumann** [comment] 2018-01-21 23:21
Haha, that would probably be it then! I think we should get your script put in the examples section of the project with notes and whatnot, or maybe you should email Polo and get them to link to it for other people to use? Or not, market competition and all. Thanks mate.

**Comment by JohnVonNeumann** [comment] 2018-01-22 00:30
Can confirm it was the dependencies, thanks again.

**Comment by rengelking** [comment] 2018-04-02 18:09
@CfirTsabari it appears that the api has been updated as there is no "subscribed" event that ever comes in, the data just starts coming in. So where you check data[1} for a 1 or 0, for subscription succes/failure, that doesn't work anymore

**Comment by s4w3d0ff** [comment] 2019-05-18 02:33
see #195

**Closed by s4w3d0ff** 2019-05-18 02:33 UTC
Labels: bug, push api
